<?php

namespace App\Controller\Admin;

use App\Model\Entity\Option;
use App\Model\Table\OptionsTable;
use App\Model\Table\TrafficsTable;

/**
 * @property \App\Model\Table\StatisticsTable $Statistics
 * @property \App\Model\Table\WithdrawsTable $Withdraws
 * @property OptionsTable $Options
 * @property TrafficsTable $Traffics
 */
class AdsController extends AppAdminController
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Options');
    }

    public function list(){
        if ($this->request->is('post')){
            $opt_adsList = $this->Options->find()->where(['name' => 'adsList'])->first();
            if (!$opt_adsList){
                $opt_adsList = $this->Options->newEntity();
            }
            $adsList = $this->getRequest()->getData('adsList',[]);
            $opt_adsList->name = 'adsList';
            $opt_adsList->value = json_encode($adsList);
            $this->Options->save($opt_adsList);
            $this->redirect(['controller' => 'Ads','action' => 'list']);
        }
        $this->set('adsList',get_option('adsList'));
    }
}
