<?php

namespace App\Controller\Admin;

use App\Model\Table\BuyerReportsTable;
use App\Model\Table\OptionsTable;
use App\Model\Table\TrafficsTable;
use Cake\Event\Event;
use Cake\Http\Exception\NotFoundException;
use Cake\ORM\TableRegistry;

/**
 * @property BuyerReportsTable $BuyerReports
 * @property TrafficsTable $Traffics
 */

class BuyerReportsController extends AppAdminController
{
    public $paginate = [
        'limit' => 10
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('BuyerReports');
        $this->loadModel('Traffics');
    }

    public function index()
    {
        $buyerReport = $this->BuyerReports->find()
            ->contain(['traffics','users'])
            ->orderAsc('BuyerReports.status')
            ->orderDesc('BuyerReports.id');
        $reports = $this->paginate($buyerReport);
        $this->set('reports',$reports);
    }

    public function edit(){
        $id = $this->getRequest()->getQuery('id');
        if (!$id) return false;
        $buyerReport = $this->BuyerReports->get($id);
        $traffic = $this->Traffics->find()->contain(['BuyerInvoices'])->where(['Traffics.id' => $buyerReport->traffic_id])->first();

        if ($this->getRequest()->is(['post','put'])){
            $traffic2_url = $this->getRequest()->getData('traffic_ver2_url');
            if (!empty($traffic2_url)) $traffic2_url = json_encode($traffic2_url);
            $data = [
                'title' => $this->getRequest()->getData('keywords'),
                'url' => $this->getRequest()->getData('url'),
                'count_day' => $this->getRequest()->getData('count_day'),
                'keywords' => $this->getRequest()->getData('keywords'),
                'img_mobile' => $this->getRequest()->getData('image_url'),
                'img_desktop' => $this->getRequest()->getData('image_url'),
                'description' => $this->getRequest()->getData('description'),
                'traffic_ver2_url' => $traffic2_url
            ];
            if ($traffic->buyer_invoice->status && $this->getRequest()->getData('status') != 'false'){
                $data['status'] = $this->getRequest()->getData('status');
            }

            $traffic = $this->Traffics->patchEntity($traffic,$data);
            if ($this->Traffics->save($traffic)){
                $buyerReport->status = 1;
                $this->BuyerReports->save($buyerReport);
                $this->Flash->success('Đã phê duyệt');
                return $this->redirect(['action' => 'index']);
            }
        }

        $this->set('traffic',$traffic);
        $this->set('buyer',$buyerReport);
    }

    public function delete($id){
        $this->getRequest()->allowMethod(['post', 'delete']);

        $buyerReport = $this->BuyerReports->findById($id)->first();

        if ($this->BuyerReports->delete($buyerReport)) {
            $this->Flash->success(__('The Buyer Report with id: {0} has been deleted.', $buyerReport->id));

            return $this->redirect(['action' => 'index']);
        }
    }
}
