<?php

namespace App\Controller\Admin;

use App\Model\Entity\Option;
use App\Model\Table\OptionsTable;
use App\Model\Table\TrafficsTable;

/**
 * @property \App\Model\Table\StatisticsTable $Statistics
 * @property \App\Model\Table\WithdrawsTable $Withdraws
 * @property OptionsTable $Options
 * @property TrafficsTable $Traffics
 */
class TopMemberController extends AppAdminController
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Options');
    }

    public function list(){
        if ($this->request->is('post')){
            $opt_topMemberList = $this->Options->find()->where(['name' => 'topMemberList'])->first();
            if (!$opt_topMemberList){
                $opt_topMemberList = $this->Options->newEntity();
            }
            $topMemberList = $this->getRequest()->getData('topMemberList',[]);
            $opt_topMemberList->name = 'topMemberList';
            $opt_topMemberList->value = json_encode($topMemberList);
            $this->Options->save($opt_topMemberList);
            $this->redirect(['controller' => 'TopMember','action' => 'list']);
        }
        $this->set('topMemberList',get_option('topMemberList'));
    }

    public function addFooter(){
        if ($this->request->is('post')){
            $urlList = $this->getRequest()->getData('add_footer',[]);
            $opt_urlList = $this->Options->find()->where(['name' => 'addFooter'])->first();
            if (!$opt_urlList){
                $opt_urlList = $this->Options->newEntity();
            }
            $opt_urlList->name = 'addFooter';
            $opt_urlList->value = $urlList;
            $this->Options->save($opt_urlList);
            $this->redirect(['controller' => 'TopMember','action' => 'addFooter']);
        }
        $this->set('adsList',get_option('adsList'));
    }
}
