<?php

namespace App\Controller\Buyer;

use App\Model\Entity\BuyerCampaign;
use App\Model\Entity\BuyerInvoice;
use App\Model\Entity\Traffic;
use App\Model\Table\BuyerCampaignsTable;
use App\Model\Table\BuyerInvoicesTable;
use App\Model\Table\BuyerReportsTable;
use App\Model\Table\DatetfsTable;
use App\Model\Table\JobtfsTable;
use App\Model\Table\TrafficsTable;
use Cake\Mailer\MailerAwareTrait;
use Cake\I18n\Time;
use Cake\Http\Exception\NotFoundException;
use Cake\Cache\Cache;
use Cake\Datasource\ConnectionManager;
use Cake\ORM\Query;
use GeoIp2\Database\Reader;

/**
 * @property BuyerCampaignsTable $BuyerCampaigns
 * @property TrafficsTable $Traffics
 * @property BuyerInvoicesTable $BuyerInvoices
 * @property DatetfsTable $Datetfs
 * @property JobtfsTable $Jobtfs
 * @property BuyerReportsTable $BuyerReports
 */

class TrafficCampaignsController extends AppBuyerController
{
    public $paginate = [
        'limit' => 10,
    ];

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('BuyerCampaigns');
        $this->loadModel('Traffics');
        $this->loadModel('BuyerInvoices');
        $this->loadModel('Datetfs');
        $this->loadModel('Jobtfs');
        $this->loadModel('BuyerReports');
        $this->loadComponent('PhpExcel');
        date_default_timezone_set('Asia/Ho_Chi_Minh');
    }

    public function index(){
        $traffics = $this->Traffics->find()
            ->contain(['BuyerCampaigns','BuyerInvoices'])
            ->where(['Traffics.user_id' => $this->Auth->user('id')]);

        if ($this->getRequest()->is(['post','put'])){
            $filter = $this->getRequest()->getData('Filter');
            if (!empty($filter['id'])) $traffics->where(['Traffics.id' => $filter['id']]);
            if ($filter['status']) $traffics->where(['Traffics.status' => $filter['status']]);
            if (!empty($filter['url'])) $traffics->where(['Traffics.url' => $filter['url']]);
            if ($filter['traffic_package_id']) $traffics->where(['BuyerCampaigns.traffic_package_id' => $filter['traffic_package_id']]);
        }

        $traffics = $traffics->orderDesc('Traffics.id');

        if ($traffics){
            foreach ($traffics as $traffic){
                $viewToday = $this->Datetfs->find()->where(['traffic_id' => $traffic->id,'date' => date('Y-m-d')])->sumOf('views');
                $traffic->viewToday = $viewToday;
            }
        }

        $data = [
            'traffics' => $traffics->all(),
            'packages' => get_option('packages'),
            'statists' => $this->buyer_statists(),
            'traffic_total' => $this->traffic_total_statists()
        ];

        $this->set('data',$data);
    }

    public function view($id = null){
        if (!$id) throw new NotFoundException(__('404 Not Found'));
        $monthData = Time::now()->format('Y-m');
        if (!empty($this->getRequest()->getQuery('month'))) $monthData = $this->getRequest()->getQuery('month');

        $traffic = $this->Traffics->find()
            ->contain(['BuyerCampaigns','BuyerInvoices'])
            ->where(['Traffics.id' => $id])->first();
        if (!$traffic) throw new NotFoundException(__('404 Not Found'));

        $traffic_view = function ($today = false) use($traffic){
            $traffic = $this->Datetfs->find()->where(['traffic_id' => $traffic->id]);
            if ($today) $traffic->where(['date' => date('Y-m-d')]);
            return $traffic->sumOf('views');
        };

        $traffic_ips = $this->Jobtfs->find()
            ->select(['ip','created'])
            ->where([
                'traffic_id' => $traffic->id,
                'status' => 1,
                'created >=' => Time::parse($monthData)->startOfMonth(),
                'created <=' => Time::parse($monthData)->endOfMonth()
            ]);
        $traffic_ips = $traffic_ips->all();
        if ($traffic_ips){
            foreach ($traffic_ips as $ip){
                $ip->country = $this->Jobtfs->get_country($ip->ip);
            }
        }

        $year_month = [];
        $start = Time::now();
        $end = Time::now()->modify('-2 month');

        while (strtotime($start->format('Y-m')) >= strtotime($end->format('Y-m'))) {
            $year_month[$start->format('Y-m')] = $start->i18nFormat('LLLL Y');
            $start = $start->modify('-1 month');
        }


        $data = [
            'traffic' => $traffic,
            'traffic_view' => $traffic_view(),
            'traffic_view_today' => $traffic_view(true),
//            'packages' => get_option('packages'),
            'statists' => $this->traffic_statists($id),
            'traffic_ips' => $traffic_ips,
            'year_month' => $year_month
        ];

        $this->set('data',$data);
    }

    public function edit($id = null){
        if (!$id) throw new NotFoundException(__('404 Not Found'));
        $traffic = $this->Traffics->find()->contain(['BuyerInvoices'])->where(['Traffics.id' => $id])->first();
        if (!$traffic) throw new NotFoundException(__('404 Not Found'));

        if ($this->getRequest()->is(['post','put'])){
            $buyerReports = $this->BuyerReports->find()->where(['traffic_id' => $id])->first();
            if (!$buyerReports) $buyerReports = $this->BuyerReports->newEntity();
            $data = $this->getRequest()->getData('edit');
            $buyerReports = $this->BuyerReports->patchEntity($buyerReports,[
                'traffic_id' => $id,
                'user_id' => $traffic->user_id,
                'status' => 0,
                'content' => json_encode($data),
                'date' => Time::now()
            ]);
            if ($this->BuyerReports->save($buyerReports)){
                $this->Flash->success(__('Yêu cầu cập nhật thành công'));
                return $this->redirect(['action' => 'index']);
            }
        }

        $this->set('traffic',$traffic);
        $this->set('packages',get_option('packages'));

    }

    public function create(){
        /**
         * @var BuyerCampaign $buyerCampaign
         * @var Traffic $traffic
         * @var BuyerInvoice $buyerInvoice
         */
        $buyerCampaign = $this->BuyerCampaigns->newEntity();

        if ($this->getRequest()->is(['post', 'put'])){
            $user = $this->Auth->user('id');
            $campaign_keywords = $this->getRequest()->getData('campaign_keywords');

            $buyerCampaign = $this->BuyerCampaigns->patchEntity($buyerCampaign,$this->getRequest()->getData());
            if (!empty($campaign_keywords) && count($campaign_keywords)) $buyerCampaign->campaign_keywords = json_encode($this->getRequest()->getData('campaign_keywords'));
            $buyerCampaign->user_id = $user;

            if ($this->BuyerCampaigns->save($buyerCampaign)){

                $buyerInvoice = $this->BuyerInvoices->newEntity();
                $buyerInvoice = $this->BuyerInvoices->patchEntity($buyerInvoice,[
                    'buyer_id' => $buyerCampaign->id,
                    'status' => 0,
                    'user_id' => $user
                ]);
                if($this->BuyerInvoices->save($buyerInvoice)){

                    if (!empty($campaign_keywords)){

                        //Add Traffics
                        $traffic_ids = [];
                        $traffic_total = 0;
                        $campaign_keywords = array_values($campaign_keywords);

                        foreach ($campaign_keywords as $campaign){
                            $package = packages()[$campaign['package']];
                            $traffic = $this->Traffics->newEntity();
                            $options = [
                                'title' => $campaign['keyword'],
                                'kind' => $campaign['kind'],
                                'count_day' => $campaign['view_per_day'],
                                'count' => $campaign['total_views'],
                                'img_mobile' => $campaign['image_url'],
                                'img_desktop' => $campaign['image_url'],
                                'keywords' => $campaign['keyword'],
                                'url' => $campaign['url'],
                                'user_id' => $user,
                                'buyer_id' => $buyerCampaign->id,
                                'invoice_id' => $buyerInvoice->id,
                                'buyer_package' => $campaign['package']
                            ];

                            switch ($campaign['package']){
                                case '2' : {
                                    $options['traffic_ver2'] = 1;
                                    break;
                                }
                                default : $options['traffic_ver2'] = 0;
                            }
//                            $options['traffic_ver2_url'] = json_encode($campaign['traffic2_url']);

                            $traffic = $this->Traffics->patchEntity($traffic,$options);
                            if ($this->Traffics->save($traffic)){
                                $traffic_ids[] = $traffic->id;
                                $traffic_total += $traffic->count * $package->price;
                            }
                        }
                        $buyerCampaign->total_amount = $traffic_total;
                        $this->BuyerCampaigns->save($buyerCampaign);
                    }

                    $buyerInvoice = $this->BuyerInvoices->get($buyerInvoice->id);
                    $buyerInvoice->traffic_ids = implode(',',$traffic_ids);
                    $this->BuyerInvoices->save($buyerInvoice);

                    $this->Flash->success('Quảng Cáo của bạn đã được tạo');
                    return $this->redirect(['controller' => 'Invoices', 'action' => 'view','id' => $buyerInvoice->id]);
                }
            }
        }

        $this->set('packages',get_option('packages'));
    }

    public function buyer_statists(){
        $statists = [];
        $c_statists = Cache::read("currentMonthDays_Buyer_{$this->Auth->user('id')}", '15min');
        if ($c_statists){
            $statists = $c_statists;
        } else {
            $start = Time::now()->startOfMonth()->format('Y-m-d');
            $end = Time::now()->endOfMonth()->format('Y-m-d');

            $traffics = $this->Traffics->find()
                ->where([
                    'user_id' => $this->Auth->user('id'),
                    'status' => 1
                ])->all();
            $n_traffics = [];
            if ($traffics){
                foreach ($traffics as $traffic){
                    $traffics_date = [];
                    $datetfs = $this->Datetfs->find()->where([
                        'traffic_id' => $traffic->id,
                        'date >=' => $start,
                        'date <=' => $end
                    ])->all();
                    foreach ($datetfs as $item){
                        if ($item){
                            $date = Time::parse($item->date)->format('Y-m-d');
                            $traffics_date[$date] = $item->views;
                        }
                    }
                    if (!count($traffics_date)) continue;
                    $n_traffics[] = $traffics_date;
                }
            }

            while (strtotime($start) <= strtotime($end)) {
                $statists[$start] = 0;
                $start = date ("Y-m-d", strtotime("+1 days", strtotime($start)));
            }

            foreach ($n_traffics as $traffic){
                foreach ($traffic as $k => $item){
                    $statists[$k] += $item;
                }
            }

            if ((bool)get_option('cache_admin_statistics', 1)) {
                Cache::write("currentMonthDays_Buyer_{$this->Auth->user('id')}", $statists, '5min');
            }
        }
        return $statists;
    }

    public function traffic_statists($id){
        $monthData = $this->getRequest()->getQuery('month');
        $statists = $date_statists = [];
        if (!empty($monthData)){
            $date_statists = $this->run_statists($id,$monthData);
        } else {
            $c_statists = Cache::read("currentMonthDays_Buyer_Traffic_{$id}_{$this->Auth->user('id')}", '15min');
            if ($c_statists){
                $date_statists = $c_statists;
            } else {
                $date_statists = $this->run_statists($id);
                if ((bool)get_option('cache_admin_statistics', 1)) {
                    Cache::write("currentMonthDays_Buyer_Traffic_{$id}_{$this->Auth->user('id')}", $date_statists, '5min');
                }
            }
        }
        return $date_statists;
    }

    public function get_country($ip)
    {
        if (!empty($_SERVER["HTTP_CF_IPCOUNTRY"])) {
            if (!in_array($_SERVER["HTTP_CF_IPCOUNTRY"], ['XX', 'T1'])) {
                return $_SERVER["HTTP_CF_IPCOUNTRY"];
            }
        }

        try {
            $reader = new Reader(CONFIG . 'binary/geoip/GeoLite2-Country.mmdb');
            $record = $reader->country($ip);
            $countryCode = (trim($record->country->isoCode)) ? $record->country->isoCode : 'Others';
        } catch (\Exception $ex) {
            $countryCode = 'Others';
        }

        return $countryCode;
    }

    public function traffic_total_statists(){
        $traffics = $this->Traffics->find()
            ->contain(['BuyerCampaigns','Datetfs'])
            ->where([
                'Traffics.user_id' => $this->Auth->user('id'),
            ])
            ->all();
        if (!$traffics) $traffics = null;

        $packages = packages();
        $traffic_total = [
            'active' => 0,
            'pause' => 0,
            'viewedToday' => 0,
            'views' => 0,
            'viewed' => 0,
            'viewedMoney' => 0,
            'allMoney' => 0
        ];

        foreach ($traffics as $k => $traffic){
            if ($traffic->status == 1) {
                $traffic_total['active'] += 1;
                $traffic_total['views'] += $traffic->count;
                $traffic_total['viewed'] += $traffic->views;
                $traffic_total['viewedMoney'] += ($traffic->views * $packages[$traffic->buyer_campaign->traffic_package_id ?? 1]->price);
                $traffic_total['allMoney'] += $traffic->count * $packages[$traffic->buyer_campaign->traffic_package_id ?? 1]->price;
            }
            if ($traffic->status == 0) $traffic_total['pause'] += 1;
        }
        $traffic_total['viewedToday'] += $this->Traffics->Datetfs->totalView($this->Auth->user('id'),true);

        return $traffic_total;
    }

    public function run_statists($id,$month = false){
        $start = Time::now()->startOfMonth()->format('Y-m-d');
        $end = Time::now()->endOfMonth()->format('Y-m-d');
        if (!empty($month)){
            $start = Time::parse($month)->startOfMonth()->format('Y-m-d');
            $end = Time::parse($month)->endOfMonth()->format('Y-m-d');
        }

        $traffics = $this->Datetfs->find()
            ->where([
                'traffic_id' => $id,
                'date >=' => $start,
                'date <=' => $end
            ])->all();
        if ($traffics){
            foreach ($traffics as $traffic){
                $statists[Time::parse($traffic->date)->format('Y-m-d')] = $traffic->views;
            }
        }

        while (strtotime($start) <= strtotime($end)) {
            $date_statists[$start] = 0;
            $start = date ("Y-m-d", strtotime("+1 days", strtotime($start)));
        }

        if (!empty($statists)){
            foreach ($statists as $k => $item){
                $date_statists[$k] += $item;
            }
        }
        return $date_statists;
    }

    public function downloadExcel($id){
        $traffic = $this->Traffics->find()->where(['id' => $id])->first();
        if (empty($traffic)) return;

        $PhpExcel=$this->PhpExcel;
        $PhpExcel->createExcel();
        $PhpExcel->setSize('A',false,true);
        $PhpExcel->setSize('B',false,true);
        $PhpExcel->writeCellValue('A1',"Camp code");
        $PhpExcel->writeCellValue('B1',"$traffic->id");
        $PhpExcel->writeCellValue('A2',"Tên chiến dịch");
        $PhpExcel->writeCellValue('B2',"$traffic->title");
        $PhpExcel->writeCellValue('A3',"URL chiến dịch");
        $PhpExcel->writeCellValue('B3',"$traffic->url");
        $PhpExcel->writeCellValue('A4',"Mỗi ngày");
        $PhpExcel->writeCellValue('B4',"$traffic->count_day");
        $PhpExcel->writeCellValue('A5',"Thống kê theo ngày");
        $PhpExcel->mergerCell('A5:B5');

        $traffic_dated = $this->Datetfs->find()
            ->where([
                'traffic_id' => $traffic->id,
                'date >=' => Time::now()->modify('-2 month')->startOfMonth()->format('Y-m-d'),
                'date <=' => Time::now()->endOfDay()->format('Y-m-d')
            ])->all();
        if (!empty($traffic_dated)){
            $index = 6;
            foreach ($traffic_dated as $k => $dated){
                $date = Time::parse($dated->date)->format('d/m/Y');
                $views = $dated->views;
                $PhpExcel->writeCellValue("A{$index}","$date");
                $PhpExcel->writeCellValue("B{$index}","$views");
                $index++;
            }
        }
        $PhpExcel->downloadFile();
    }
}
