<?php

namespace App\Controller\Buyer;

use App\Model\Entity\BuyerCampaign;
use App\Model\Entity\BuyerInvoice;
use App\Model\Entity\Traffic;
use App\Model\Table\BuyerCampaignsTable;
use App\Model\Table\BuyerInvoicesTable;
use App\Model\Table\TrafficsTable;
use Cake\Mailer\MailerAwareTrait;
use Cake\I18n\Time;
use Cake\Http\Exception\NotFoundException;
use Cake\Cache\Cache;
use Cake\Datasource\ConnectionManager;

/**
 * @property BuyerInvoicesTable $BuyerInvoices
 */

class InvoicesController extends AppBuyerController
{
    public $paginate = [
        'limit' => 10,
    ];

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('BuyerInvoices');
        date_default_timezone_set('Asia/Ho_Chi_Minh');
    }

    public function index(){
        /**
         * @var BuyerInvoice $buyerInvoice
         */

        $buyerInvoice = $this->BuyerInvoices->find()
            ->contain(['BuyerCampaigns'])
            ->where(['BuyerInvoices.user_id' => $this->Auth->user('id')])->orderDesc('BuyerInvoices.id');
        $buyerInvoice = $this->paginate($buyerInvoice);

        $this->set('invoices',$buyerInvoice);
    }

    public function view($id){
        if (!$id) {
            throw new NotFoundException(__('404 Not Found'));
        }

        /**
         * @var BuyerInvoice $buyerInvoice
         */

        $banks = [];
        $buyerInvoice = $this->BuyerInvoices->find()
            ->contain(['BuyerCampaigns'])
            ->where(['BuyerInvoices.id' => $id])
            ->first();

        if (!$buyerInvoice){
            throw new NotFoundException(__('404 Not Found'));
        }

        if(get_option('banktransfer_enable') == 'yes'){
            $banks['banktransfer'] = get_option('banktransfer_instructions');
        };

        $this->set('banks',$banks);
        $this->set('invoice',$buyerInvoice);
    }

    public function checkout(){
        if ($this->getRequest()->is(['post','put'])){
            $invoice = $this->BuyerInvoices->get($this->getRequest()->getData('invoice_id'));
            $invoice->payment_method = $this->getRequest()->getData('payment_method');
            if ($this->BuyerInvoices->save($invoice)){
                $this->redirect(['controller' => 'Invoices','action' => 'view','id' => $invoice->id]);
            }
        }
    }
}
