<?php

namespace App\Controller\Buyer;

use App\Model\Table\PagesTable;
use Cake\Mailer\MailerAwareTrait;
use Cake\I18n\Time;
use Cake\Http\Exception\NotFoundException;
use Cake\Cache\Cache;
use Cake\Datasource\ConnectionManager;

/**
 * @property PagesTable $Pages
 */
class OptionsController extends AppBuyerController
{
    protected $conn;
    protected $table = 'options';

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->conn = ConnectionManager::get('default');
        $this->loadModel('Pages');
    }

    public function package(){
        if ($this->Auth->user('role') != 'admin'){
            throw new NotFoundException(__('404 Not Found'));
        }
        if ($this->getRequest()->is(['post','put'])){
            $packages = $this->getRequest()->getData('packages');
            if (empty($packages)) return $this->redirect(['controller' => 'Packages','action' => 'index']);
            $packages = json_encode($packages);

            $options = $this->conn->newQuery();
            $options->select('*')->from($this->table)->where(['name' => 'packages']);
            $options = $options->execute()->fetch();
            if (!$options){
                $this->insertData($this->table,['name' => 'packages','value' => $packages]);
            } else {
                $this->update($this->table,['name' => 'packages'],['value' => $packages]);
            }
            $this->redirect(['_name' => 'buyer_option_packages']);
        }

        $this->set('packages',get_option('packages'));
    }

    public function notification(){
        if ($this->Auth->user('role') != 'admin'){
            throw new NotFoundException(__('404 Not Found'));
        }
        $pages = $this->Pages->find()->where(['published' => 1])->orderDesc('id')->all();

        if ($this->getRequest()->is(['post','put'])){
            if ($page = $this->getRequest()->getData('page')){
                if (!get_option('buyer_page')){
                    $this->insertData($this->table,['name' => 'buyer_page','value' => $page]);
                } else {
                    $this->update($this->table,['name' => 'buyer_page'],['value' => $page]);
                }
            }

            if ($ember_code = $this->getRequest()->getData('ember_code')){
                if (!get_option('ember_code')){
                    $this->insertData($this->table,['name' => 'ember_code','value' => $ember_code]);
                } else {
                    $this->update($this->table,['name' => 'ember_code'],['value' => $ember_code]);
                }
            }

            if ($nf_1 = $this->getRequest()->getData('nf_1')){
                if (!get_option('nf_1')){
                    $this->insertData($this->table,['name' => 'nf_1','value' => $nf_1]);
                } else {
                    $this->update($this->table,['name' => 'nf_1'],['value' => $nf_1]);
                }
            }

            if ($nf_2 = $this->getRequest()->getData('nf_2')){
                if (!get_option('nf_1')){
                    $this->insertData($this->table,['name' => 'nf_2','value' => $nf_2]);
                } else {
                    $this->update($this->table,['name' => 'nf_2'],['value' => $nf_2]);
                }
            }

            if ($info_banking = $this->getRequest()->getData('info_banking')){
                if (!get_option('nf_1')){
                    $this->insertData($this->table,['name' => 'info_banking','value' => $info_banking]);
                } else {
                    $this->update($this->table,['name' => 'info_banking'],['value' => $info_banking]);
                }
            }

            $this->Flash->success('Cập nhật thành công');

            $this->redirect(['_name' => 'buyer_option_notification']);
        }

        $this->set('pages',$pages);
    }

    public function update($table,$condition,$data){
        $query = $this->conn->newQuery();
        $query->update($table)->set($data)->where($condition);
        $statement = $query->execute();
        return $statement->execute();
//        return $this->conn->update($table,$data,$condition);
    }

    public function insertData($table,$data){
        return $this->conn->insert($table,$data);
    }
}
