<?php

namespace App\Controller\Admin;

use App\Model\Table\MemberReportsTable;
use App\Model\Table\OptionsTable;
use App\Model\Table\TrafficsTable;
use Cake\Event\Event;
use Cake\Http\Exception\NotFoundException;
use Cake\ORM\TableRegistry;

/**
 * @property MemberReportsTable $MemberReports
 * @property TrafficsTable $Traffics
 */

class MemberReportsController extends AppAdminController
{
    public $paginate = [
        'limit' => 10
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('MemberReports');
        $this->loadModel('Traffics');
    }

    public function index()
    {
        $memberReport = $this->MemberReports->find()
            ->contain(['traffics'])
            ->where(['MemberReports.status' => 0])
            ->orderDesc('MemberReports.id');
        $reports = $this->paginate($memberReport);
        $this->set('reports',$reports);
    }

    public function edit(){
        $id = $this->getRequest()->getQuery('id');
        if (!$id) return false;
        $buyerReport = $this->BuyerReports->get($id);
        $traffic = $this->Traffics->find()->contain(['BuyerInvoices'])->where(['Traffics.id' => $buyerReport->traffic_id])->first();

        if ($this->getRequest()->is(['post','put'])){
            $data = [
                'title' => $this->getRequest()->getData('keywords'),
                'url' => $this->getRequest()->getData('url'),
                'count_day' => $this->getRequest()->getData('count_day'),
                'keywords' => $this->getRequest()->getData('keywords'),
                'img_mobile' => $this->getRequest()->getData('image_url'),
                'img_desktop' => $this->getRequest()->getData('image_url'),
                'description' => $this->getRequest()->getData('description'),
            ];
            if ($traffic->buyer_invoice->status && $this->getRequest()->getData('status') != 'false'){
                $data['status'] = $this->getRequest()->getData('status');
            }

            $traffic = $this->Traffics->patchEntity($traffic,$data);
            if ($this->Traffics->save($traffic)){
                $buyerReport->status = 1;
                $this->BuyerReports->save($buyerReport);
                $this->Flash->success('Đã phê duyệt');
                return $this->redirect(['action' => 'index']);
            }
        }

        $this->set('traffic',$traffic);
        $this->set('buyer',$buyerReport);
    }

    public function delete($id){
        $this->getRequest()->allowMethod(['post', 'delete']);

        $memberReport = $this->MemberReports->findById($id)->first();
        $memberReport->status = 1;

        if ($this->MemberReports->save($memberReport)) {
            $this->Flash->success(__('The Member Report with id: {0} has been deleted.', $memberReport->id));

            return $this->redirect(['action' => 'index']);
        }
    }

    public function deleteAll(){
        $this->getRequest()->allowMethod(['post', 'delete']);

        $members = $this->MemberReports->find()->all();
        if ($members){
            foreach ($members as $member){
                $this->MemberReports->delete($member);
            }
        }
        $this->Flash->success(__('The Member Report has been deleted.'));
        return $this->redirect(['action' => 'index']);
    }
}
