<?php

namespace App\Controller\Admin;

use App\Model\Table\OptionsTable;
use Cake\Event\Event;
use Cake\Http\Exception\NotFoundException;
use Cake\ORM\TableRegistry;
use Cake\Datasource\ConnectionManager;

class PackagesController extends AppAdminController
{
    protected $conn;
    protected $table = 'options';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->conn = ConnectionManager::get('default');
        $this->loadModel('Options');
    }

    public function index()
    {
        if ($this->getRequest()->is(['post','put'])){
            $packages = $this->getRequest()->getData('packages');
            if (empty($packages)) return $this->redirect(['controller' => 'Packages','action' => 'index']);
            $packages = json_encode($packages);

            $options = $this->conn->newQuery();
            $options->select('*')->from($this->table)->where(['name' => 'packages']);
            $options = $options->execute()->fetch();
            if (!$options){
                $this->insertData($this->table,['name' => 'packages','value' => $packages]);
            } else {
                $this->update($this->table,['name' => 'packages'],['value' => $packages]);
            }
            $this->redirect(['controller' => 'Packages','action' => 'index']);
        }

        $this->set('packages',get_option('packages'));
    }

    public function update($table,$condition,$data){
        $query = $this->conn->newQuery();
        $query->update($table)->set($data)->where($condition);
        $statement = $query->execute();
        return $statement->execute();
    }

    public function insertData($table,$data){
        return $this->conn->insert($table,$data);
    }

}
